### PR TITLE
Allow puppetlabs/stdlib 6.x and puppet 6.x.

### PR DESCRIPTION
**Pull request by pillarsdotnet**
Tests appear to be broken.

### CODE REVIEW

**Comment by pillarsdotnet** [comment]
[Errors](https://travis-ci.org/elastic/puppet-logstash/jobs/566984193) appear unrelated to PR:
- `Failed to retrieve Augeas version: cannot load such file -- augeas`
- `'/usr/bin/yum -d 0 -e 0 -y install logstash' returned 1: Error Downloading Packages`
- `Error: /Stage[main]/Elastic_stack::Repo/Yumrepo[elastic]: Could not evaluate: undefined method `_' for Puppet::Type::Yumrepo::ProviderInifile:Class`
- `No output has been received in the last 10m0s`
- `Failed to fetch http://deb.debian.org/debian/dists/wheezy/main/binary-amd64/Packages  404  Not Found`
- `Failed to fetch http://deb.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  404  Not Found`

**Comment by pillarsdotnet** [comment]
Still getting `package not found` errors when installing the logstash package.  Not sure why.  Help?

**Comment by pillarsdotnet** [comment]
@jarpy

**Comment by cubiclelord** [comment]
Any luck fixing the tests here?  I'd love to see these versions increased and a new module released ... :)

**Comment by jarpy** [comment]
#394 Does a lot of the work towards updating the tests, but still needs work to satisfy #393 (and probably other things). If anyone wants to look at [the Dockerfiles](https://github.com/elastic/puppet-logstash/tree/master/spec/acceptance/nodesets), please jump in on the `logstash7` branch.

You can test a distro locally like this:

```
env LOGSTASH_VERSION=7.3.0 BEAKER_set=ubuntu-1604 PUPPET_VERSION=6.0.10 bundle exec rake beaker
```

cc @mgreau

**Comment by ekohl** [comment]
This has been superseded and the module already allows newer versions.

**Pull request closed without merging**
